spring:
  application:
    name: shopping-store
  config:
    import: "configserver:"

  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: config-server
        enabled: true
      retry:
        max-interval: 10000
        use-random-policy: true

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka